language: rust
rust:
  - stable

before_script: |
  rustup component add rustfmt &&
  rustup compoent add clippy
script: |
  cargo fmt -- --check &&
  cargo clippy -- -D clippy &&
  cargo build --verbose &&
  cargo test  --verbose
cache: cargo
